n = input('Escreva algo: ')
print(f'o tipo primitivo de {n} é {type(n)}')
print(f'Só tem espaços? {n.isspace()}')
print(f'É alfanumérico? {n.isalnum()}')
print(f'É alfabético? {n.isalpha()}')
print(f'É numérico {n.isnumeric()}')
print(f'Só tem maiúsculas? {n.isupper()}')
print(f'Só tem minúsculas? {n.islower()}')
print(f'Está titulado? {n.istitle()}')