# O programa deve mostrar a tabuada do número digitado
n = int(input('Digite um número inteiro: '))
print(f'A tabuada do número {n} é:')
print('-'*15)
print(f'1 x {n} =', n*1)
print(f'2 x {n} =', n*2)
print(f'3 x {n} =', n*3)
print(f'4 x {n} =', n*4)
print(f'5 x {n} =', n*5)
print(f'6 x {n} =', n*6)
print(f'7 x {n} =', n*7)
print(f'8 x {n} =', n*8)
print(f'9 x {n} =', n*9)
print(f'10 x {n} =', n*10)
print('-'*15)
